CREATE TABLE TempEmployees (
    EmployeeID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Department VARCHAR(50)
);

INSERT INTO Employees (EmployeeID, FirstName, LastName, Department) 
VALUES
(1, 'John', 'Doe', 'IT'),
(2, 'Jane', 'Smith', 'HR'),
(3, 'Alice', 'Johnson', 'Marketing'),
(4, 'Eve', 'Stewart', 'Finance'),
(5, 'Michael', 'Brown', 'IT'),
(6, 'Emily', 'Davis', 'HR'),
(7, 'William', 'Miller', 'Marketing'),
(8, 'Olivia', 'Wilson', 'Finance'),
(9, 'Daniel', 'Moore', 'IT'),
(10, 'Ava', 'Taylor', 'HR'),
(11, 'James', 'Anderson', 'Marketing'),
(12, 'Sophia', 'Martinez', 'Finance'),
(13, 'Benjamin', 'Hernandez', 'IT'),
(14, 'Mia', 'Lopez', 'HR'),
(15, 'Elijah', 'Gonzalez', 'Marketing'),
(16, 'Charlotte', 'Young', 'Finance'),
(17, 'Ethan', 'King', 'IT'),
(18, 'Amelia', 'Scott', 'HR'),
(19, 'Alexander', 'Green', 'Marketing'),
(20, 'Harper', 'Adams', 'Finance'),
(21, 'Daniel', 'Baker', 'IT'),
(22, 'Mila', 'Garcia', 'HR'),
(23, 'Logan', 'Perez', 'Marketing'),
(24, 'Evelyn', 'Turner', 'Finance'),
(25, 'Michael', 'Cooper', 'IT'),
(26, 'Luna', 'Ross', 'HR'),
(27, 'Henry', 'Edwards', 'Marketing'),
(28, 'Layla', 'Collins', 'Finance'),
(29, 'Sebastian', 'Stewart', 'IT'),
(30, 'Zoe', 'Morris', 'HR'),
(31, 'Carter', 'Nguyen', 'Marketing'),
(32, 'Penelope', 'Hill', 'Finance'),
(33, 'Jayden', 'Flores', 'IT'),
(34, 'Aria', 'Sullivan', 'HR'),
(35, 'Gabriel', 'Campbell', 'Marketing'),
(36, 'Ellie', 'Bennett', 'Finance'),
(37, 'John', 'Richardson', 'IT'),
(38, 'Nora', 'Coleman', 'HR'),
(39, 'Isaac', 'Barnes', 'Marketing'),
(40, 'Violet', 'Long', 'Finance'),
(41, 'Owen', 'Mitchell', 'IT'),
(42, 'Hannah', 'Murphy', 'HR'),
(43, 'Levi', 'Ward', 'Marketing'),
(44, 'Stella', 'Torres', 'Finance'),
(45, 'David', 'Russell', 'IT'),
(46, 'Skylar', 'Foster', 'HR'),
(47, 'Julian', 'Peterson', 'Marketing'),
(48, 'Bella', 'Gray', 'Finance'),
(49, 'Joseph', 'Reed', 'IT'),
(50, 'Aubrey', 'Morgan', 'HR');

CREATE TABLE EmployeeNamesConcatenated AS
SELECT EmployeeID, CONCAT(FirstName, ' ', LastName) AS FullName, Department
FROM TempEmployees;
